stages:
    - build

variables:
    MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
    IMAGE_TAG: "docker.campusonline.community/studo/studo-services"

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - /var/maven/.m2

build:
    image: maven:3-openjdk-11
    stage: build
    only:
        - snapshot
    tags:
        - co-cloud
    script:
        - mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=$BUILD_TAG
        - mvn $MAVEN_CLI_OPTS -DskipTests=true package -Dquarkus.profile=prod
    artifacts:
        paths:
            - target/quarkus-app/*