stages:
    - build
    - build-docker

variables:
    MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
    CONTAINER_IMAGE: "docker.campusonline.community/studo/studo-services:snapshot"

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - /var/maven/.m2

build:
    image: maven:3-openjdk-11
    stage: build
    only:
        - snapshot
    tags:
        - co-cloud
    script:
        - mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=$BUILD_TAG
        - mvn $MAVEN_CLI_OPTS -DskipTests=true package deploy -Dquarkus.profile=prod
    artifacts:
        paths:
            - target/quarkus-app/*

build-docker:
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [ "" ]
    stage: build-docker
    only:
        - snapshot
    tags:
        - co-cloud
    script:
        - echo "build docker image ..."
        - mkdir -p /kaniko/.docker
        - echo "{\"auths\":{\"docker.campusonline.community\":{\"username\":\"${DOCKER_USER}\",\"password\":\"${DOCKER_PASSWORD}\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/src/main/docker/Dockerfile --destination ${CONTAINER_IMAGE}
