stages:
    - build

variables:
    MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
    QUARKUS_CONTAINER_IMAGE_BUILD: "false"
    QUARKUS_CONTAINER_IMAGE_PUSH: "false"
    QUARKUS_CONTAINER_IMAGE_REGISTRY: "docker.campusonline.community"
    QUARKUS_CONTAINER_IMAGE_GROUP: "studo"
    QUARKUS_CONTAINER_IMAGE_NAME: "studo-services"
    QUARKUS_CONTAINER_IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}"
    QUARKUS_CONTAINER_IMAGE_USERNAME: "${DOCKER_USER}"
    QUARKUS_CONTAINER_IMAGE_PASSWORD: "${DOCKER_PASSWORD}"

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - /var/maven/.m2

build-docker:
    image: maven:latest
    stage: build
    only:
        - snapshot
    tags:
        - co-cloud
    variables:
        QUARKUS_CONTAINER_IMAGE_BUILD: "true"
        QUARKUS_CONTAINER_IMAGE_PUSH: "true"
        VERSION: $CI_COMMIT_SHORT_SHA
    script:
        - mvn $MAVEN_CLI_OPTS clean versions:set -DnewVersion=$VERSION
        - mvn $MAVEN_CLI_OPTS clean -Dmaven.deploy.skip=true deploy
    artifacts:
        paths:
            - target/quarkus-app/*
