### Obtain a JWT access token from openid-connect endpoint
POST {{auth-server-url}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{client-id}}&client_secret={{client-secret}}

> {%
client.test("Keycloak Access Token successfully received.", function() {
    client.global.set("access_token", response.body.access_token);
    client.assert(!!client.global.get("access_token"), "Access Token is not null");
});
%}

### we check the test endpoint, because to original endpoint is very long running
GET http://localhost:8080/studo/services/api/rest/attendance/test
Authorization: Bearer {{access_token}}

### check if the endpoint can be accessed without access token
GET http://localhost:8080/studo/services/api/rest/attendance/hello-world

### check if a anonymous client does not have access to the secure hello world endpoint
GET http://localhost:8080/studo/services/api/rest/attendance/secure-hello-world

### check if the dal client has access to the secure-hello-world, because of its scope studo-services.read
GET http://localhost:8080/studo/services/api/rest/attendance/secure-hello-world
Authorization: Bearer {{access_token}}

###
GET https://trunkline.tugraz.at/trunk_dev/co/studo/services/api/attendance/redirect