GRANT SELECT ON TUG_NEW.PU_LV_ERHEBUNG_V TO STUDO_SERVICES WITH GRANT OPTION;
/
GRANT SELECT ON TUG_NEW.PU_LV_TE_RESOURCEN_V TO STUDO_SERVICES WITH GRANT OPTION;
/
GRANT SELECT ON TUG_NEW.PU_LV_GRUPPEN_V TO STUDO_SERVICES WITH GRANT OPTION;
/
GRANT SELECT ON TUG_NEW.PU_LV_GRP_LEHRENDE_V TO STUDO_SERVICES WITH GRANT OPTION;
/
GRANT SELECT ON TUG_NEW.PU_LV_TEILNEHMER_FIXPLATZ_V TO STUDO_SERVICES WITH GRANT OPTION;
/
GRANT SELECT ON TUG_NEW.PU_PERS_ORG_FUNK_DE_FUNKTYP_V TO STUDO_SERVICES WITH GRANT OPTION;
/
GRANT SELECT ON TUG_NEW.PU_IDENTITAETEN_V TO STUDO_SERVICES WITH GRANT OPTION;
/
GRANT SELECT ON TUG_NEW.PU_ORG_V TO STUDO_SERVICES WITH GRANT OPTION;
/
GRANT SELECT ON TUG_NEW.PU_PERSONEN_V TO STUDO_SERVICES WITH GRANT OPTION;
/
GRANT SELECT ON STUD.PU_ST_PERSONEN_V TO STUDO_SERVICES WITH GRANT OPTION;
/
GRANT SELECT ON STUD.PU_STUDIEN_2_V TO STUDO_SERVICES WITH GRANT OPTION;
/
